config/routes.rb
Rails.application.routes.draw do
  # Customize devise routes (eg, change users/sign_in to 'login')
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
	
  # about, & contact are static pages (hence why they use just 'get' vs. 'resources')
	# Customize show route for portolios (want it to be /portfolio vs. /portfolios). Also assign it custom prefix portfolio_show
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id/', to: 'portfolios#show', as: 'portfolio_show'

  # Change route from pages/about to just about. Point about route to about action in pages controller.
  # controller goes on left of #; action on right
  # Note: You can pass in anything as route name (eg, 'about-me' instead of 'about')
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  # Create toggle_status route
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  # Set root path (home page) to pages#home (pages controller, home action)
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies

  # Will allow us to create single portfolio item & then slide
    # in multiple technologies
  accepts_nested_attributes_for :technologies, 
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  include Placeholder

  validates_presence_of :title, :body, :main_image, :thumb_image

  # Class method for defining scope. self - referencing particular 
    # portfolio item when it's called (like 'this' in JS)
  def self.angular
    where(subtitle: "Angular")
  end

  def self.by_position
    order("position ASC")
  end

  # Another method to define scope (use scope keyword)
  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby on Rails") }

  # After portfolio item has been initialized (when new action
    # has been called), set default value
  after_initialize :set_defaults

  # If we just did =, these defaults would overwrite existing 
    # images. 
  # ||= is a shortcut for the following code:
    # if self.main_image == nil
    #   self.main_image = "http://placehold.it/600x400"
    # end
  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :show, :update, :destroy]
  layout 'portfolio'

  access all: [:show, :index, :angular], user: {except: [:destroy, :create, :new, :update, :edit]}, site_admin: :all

  # Index Action. Call Portfolio model & make available to view
  # thru @portfolio_items var.
  def index
    # Filter items so only items with angular subtitle appear
      # This uses the custom scope we created in Portfolio 
      # model file.
    #@portfolio_items = Portfolio.angular 
    # Filter to ruby on rails subtitle
    #@portfolio_items = Portfolio.ruby_on_rails_portfolio_items
    @portfolio_items = Portfolio.by_position
  end

  # Create custom angular method that filter by angular subtitle
  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  # New Action - renders form to create new portfolio item.
  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  # Create Action
  def create
    # Specify to Rails the params that we will allow thru
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  # Edit Action
  def edit
  end

  # Update Action
 def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'The record successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # Show Action
  def show
  end

  # Destroy Action: delete record & then redirect user
  def destroy
    # Destroy/delete the record
    @portfolio_item.destroy

    # Redirect user after destroy occurs
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Record was removed.' }
    end
  end

  # Methods underneath private are only to be used inside Portfolio Controller class
  private

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      technologies_attributes: [:name]
                                     )
  end

  # Find given portfolio item
  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<!-- Form to create new portfolio item -->
<!-- form_for = method. It expects an argument(portfolio_item).
     We need to make @portfolio_item available for controller -->
<%= form_for(@portfolio_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_area :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <ul>
    <!-- f = block var (line 6) -->
    <%= f.fields_for :technologies do |technology_form| %>
      <li>
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
  <!-- Have title link to portfolio item show page -->
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>

  <p><%= portfolio_item.subtitle %></p>

  <p><%= portfolio_item.body %></p>
  
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <!-- Link to edit page -->
  <%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
  <!-- Link to delete portfolio item. method:delete tells Rails that we want to perform delete action vs. just route to show page. We don't have to pass method thru to show page b/c default method is get. -->
  <%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
  <%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit This Portfolio Item</h1>

<%= render 'form', portfolio_item: @portfolio_item  %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<!-- Link to add new portfolio item via link_to method -->
<%= link_to "Create New Item", new_portfolio_url if logged_in?(:site_admin) %>

<!-- Since the partial name doesn't match up to controller name (controller is portfolios vs. portfolio_items), we have to declare that this is a partial -->
<%= render partial: 'portfolio_item', collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<h1>Create a New Portfolio Item</h1>

<!-- Pass thru @portfolio_item instance var in portfolio_item var -->
<%= render 'form', portfolio_item: @portfolio_item  %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image %>

<h1><%= @portfolio_item.title %></h1>

<em><%= @portfolio_item.subtitle %></em>

<p><%= @portfolio_item.body %></p>

<h2>Technologies Used</h2>

<% @portfolio_item.technologies.each do |t| %>
  <p><%= t.name %></p>
<% end %>