config/routes.rb
Rails.application.routes.draw do
  # Customize devise routes (eg, change users/sign_in to 'login')
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
	
  # about, & contact are static pages (hence why they use just 'get' vs. 'resources')
	# Customize show route for portolios (want it to be /portfolio vs. /portfolios). Also assign it custom prefix portfolio_show
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id/', to: 'portfolios#show', as: 'portfolio_show'

  # Change route from pages/about to just about. Point about route to about action in pages controller.
  # controller goes on left of #; action on right
  # Note: You can pass in anything as route name (eg, 'about-me' instead of 'about')
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  # Create toggle_status route
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  # Set root path (home page) to pages#home (pages controller, home action)
  root to: 'pages#home'
end

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Julia Martin</h3>
    <nav class="nav nav-masthead justify-content-center">
      <%= link_to "Home", root_path, class: 'nav-link active' %>
      <%= link_to "About Me", about_me_path, class: 'nav-link' %>
      <%= link_to "Contact", contact_path, class: 'nav-link' %>
      <%= link_to "Blog", blogs_path, class: 'nav-link' %>
      <%= link_to "Portfolio", portfolios_path, class: 'nav-link' %>
    </nav>
  </div>
</header>

app/views/shared/_nav.html.erb
<!-- Navbar -->
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>